# Generated by Django 5.1.6 on 2026-02-27 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('template_type', models.CharField(choices=[('sem_pausa', 'Sem pausa'), ('muitas_pausas', 'Muitas pausas'), ('status_irregular', 'Status irregular'), ('supervisor_alerta', 'Supervisor alerta'), ('notificacao_generica', 'Notificacao generica')], max_length=50, verbose_name='Tipo de template')),
                ('channel', models.CharField(choices=[('chatseguro', 'ChatSeguro'), ('email', 'E-mail'), ('teams', 'Microsoft Teams'), ('slack', 'Slack'), ('webhook', 'Webhook')], max_length=30, verbose_name='Canal')),
                ('subject', models.CharField(blank=True, max_length=200, null=True, verbose_name='Assunto')),
                ('body', models.TextField(verbose_name='Conteudo')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versao')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_message_templates', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Template de mensagem',
                'verbose_name_plural': 'Templates de mensagem',
                'indexes': [models.Index(fields=['template_type', 'channel', 'active'], name='idx_msgtpl_type_chan_act')],
            },
        ),
    ]
