# Generated by Django 4.2.16 on 2026-03-05

from django.db import migrations


def seed_assistant_templates(apps, schema_editor):
    MessageTemplate = apps.get_model("messaging", "MessageTemplate")

    templates = [
        {
            "name": "pause_overflow",
            "template_type": "muitas_pausas",
            "channel": "chatseguro",
            "subject": "",
            "body": (
                "Agente {{ agent_name }}: voce excedeu o limite de pausa em "
                "{{ overflow_minutes }} minutos hoje."
            ),
        },
        {
            "name": "pause_warning",
            "template_type": "sem_pausa",
            "channel": "chatseguro",
            "subject": "",
            "body": (
                "Agente {{ agent_name }}: atencao ao nivel operacional. "
                "No momento, nao e recomendado iniciar pausa."
            ),
        },
        {
            "name": "supervisor_alert",
            "template_type": "supervisor_alerta",
            "channel": "chatseguro",
            "subject": "",
            "body": (
                "Alerta de supervisao: {{ people_in_pause }} pessoas em pausa "
                "tipo {{ pause_type }}."
            ),
        },
    ]

    for item in templates:
        MessageTemplate.objects.update_or_create(
            name=item["name"],
            channel=item["channel"],
            defaults={
                "template_type": item["template_type"],
                "subject": item["subject"],
                "body": item["body"],
                "active": True,
                "version": 1,
            },
        )


def unseed_assistant_templates(apps, schema_editor):
    MessageTemplate = apps.get_model("messaging", "MessageTemplate")
    MessageTemplate.objects.filter(
        name__in=["pause_overflow", "pause_warning", "supervisor_alert"],
        channel="chatseguro",
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_assistant_templates, unseed_assistant_templates),
    ]
