# Generated by Django 5.1.6 on 2026-02-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('channel', models.CharField(choices=[('chatseguro', 'ChatSeguro'), ('email', 'E-mail'), ('teams', 'Microsoft Teams'), ('slack', 'Slack'), ('webhook', 'Webhook')], max_length=30, verbose_name='Canal')),
                ('enabled', models.BooleanField(default=True, verbose_name='Habilitada')),
                ('config_json', models.JSONField(default=dict, verbose_name='Configuracao JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Integracao',
                'verbose_name_plural': 'Integracoes',
                'indexes': [models.Index(fields=['channel', 'enabled'], name='idx_integ_channel_en')],
            },
        ),
    ]
