# Generated by Django 4.2.16 on 2026-03-09 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assistant', '0002_assistantactionlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistantconversation',
            options={'ordering': ['-updated_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='assistantmessage',
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.AddField(
            model_name='assistantconversation',
            name='is_persistent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assistantconversation',
            name='origin',
            field=models.CharField(choices=[('widget', 'Widget'), ('page', 'Page')], default='widget', max_length=20),
        ),
        migrations.AddField(
            model_name='assistantconversation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='assistantconversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='assistantconversation',
            name='title',
            field=models.CharField(blank=True, default='Nova conversa', max_length=200),
        ),
        migrations.AlterField(
            model_name='assistantmessage',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20),
        ),
        migrations.CreateModel(
            name='AssistantUserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_saved_conversations', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_user_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
        migrations.CreateModel(
            name='AssistantAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(choices=[('widget', 'Widget'), ('page', 'Page')], default='widget', max_length=20)),
                ('input_text', models.TextField()),
                ('scope_classification', models.CharField(blank=True, default='', max_length=40)),
                ('capability_classification', models.CharField(blank=True, default='', max_length=40)),
                ('capability_id', models.CharField(blank=True, default='', max_length=100)),
                ('tools_attempted_json', models.JSONField(default=list)),
                ('tools_succeeded_json', models.JSONField(default=list)),
                ('block_reason', models.CharField(blank=True, default='', max_length=100)),
                ('fallback_reason', models.CharField(blank=True, default='', max_length=100)),
                ('final_response_status', models.CharField(choices=[('completed', 'Completed'), ('blocked_scope', 'Blocked scope'), ('blocked_capability', 'Blocked capability'), ('blocked_limit', 'Blocked limit'), ('no_data', 'No data'), ('disabled', 'Disabled'), ('config_error', 'Config error'), ('temporary_failure', 'Temporary failure'), ('fail_safe', 'Fail-safe')], default='completed', max_length=40)),
                ('response_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='assistant.assistantconversation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
