# Generated by Django 4.2.16 on 2026-03-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_alter_assistantconversation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantauditlog',
            name='event_type',
            field=models.CharField(choices=[('chat_message', 'Chat message'), ('page_conversation_created', 'Page conversation created'), ('widget_session_saved', 'Widget session saved'), ('widget_session_ended', 'Widget session ended'), ('conversation_deleted', 'Conversation deleted')], default='chat_message', max_length=40),
        ),
        migrations.AlterField(
            model_name='assistantauditlog',
            name='final_response_status',
            field=models.CharField(choices=[('completed', 'Completed'), ('blocked_scope', 'Blocked scope'), ('blocked_capability', 'Blocked capability'), ('blocked_limit', 'Blocked limit'), ('no_data', 'No data'), ('disabled', 'Disabled'), ('config_error', 'Config error'), ('tool_failure', 'Tool failure'), ('temporary_failure', 'Temporary failure'), ('fail_safe', 'Fail-safe')], default='completed', max_length=40),
        ),
    ]
