# Generated by Django 5.1.6 on 2026-02-27 15:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_operador', models.PositiveIntegerField(unique=True, verbose_name='Codigo do operador')),
                ('nm_agente', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('nm_agente_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo do agente')),
                ('nr_ramal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ramal')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Agente',
                'verbose_name_plural': 'Agentes',
                'ordering': ['cd_operador'],
            },
        ),
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(choices=[('sync', 'Sincronizacao'), ('cadencia', 'Cadencia'), ('irregulares', 'Irregulares'), ('notificacoes', 'Notificacoes'), ('relatorios', 'Relatorios')], max_length=80, verbose_name='Nome do job')),
                ('started_at', models.DateTimeField(verbose_name='Inicio')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Fim')),
                ('status', models.CharField(choices=[('RUNNING', 'Em execucao'), ('SUCCESS', 'Sucesso'), ('ERROR', 'Erro')], max_length=20, verbose_name='Status')),
                ('summary', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Resumo')),
                ('error_detail', models.TextField(blank=True, null=True, verbose_name='Detalhes do erro')),
            ],
            options={
                'verbose_name': 'Execucao de job',
                'verbose_name_plural': 'Execucoes de jobs',
                'indexes': [models.Index(fields=['job_name', 'started_at'], name='idx_jobrun_name_start')],
            },
        ),
        migrations.CreateModel(
            name='AgentDayStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_operador', models.PositiveIntegerField(db_index=True, verbose_name='Codigo do operador')),
                ('data_ref', models.DateField(db_index=True, verbose_name='Data de referencia')),
                ('qtd_pausas', models.PositiveIntegerField(default=0, verbose_name='Quantidade de pausas')),
                ('tempo_pausas_seg', models.PositiveIntegerField(default=0, verbose_name='Tempo de pausas em segundos')),
                ('ultima_pausa_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Ultimo inicio de pausa')),
                ('ultima_pausa_fim', models.DateTimeField(blank=True, null=True, verbose_name='Ultimo fim de pausa')),
                ('ultimo_logon', models.DateTimeField(blank=True, null=True, verbose_name='Ultimo logon')),
                ('ultimo_logoff', models.DateTimeField(blank=True, null=True, verbose_name='Ultimo logoff')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_stats', to='monitoring.agent', verbose_name='Agente')),
            ],
            options={
                'verbose_name': 'Estatistica diaria do agente',
                'verbose_name_plural': 'Estatisticas diarias dos agentes',
                'indexes': [models.Index(fields=['agent', 'data_ref'], name='idx_agday_agent_data')],
                'constraints': [models.UniqueConstraint(fields=('agent', 'data_ref'), name='uniq_agentdaystats_agent_date')],
            },
        ),
        migrations.CreateModel(
            name='AgentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, default='legacy', max_length=30, verbose_name='Fonte')),
                ('source_event_hash', models.CharField(db_index=True, max_length=64, verbose_name='Hash do evento na fonte')),
                ('cd_operador', models.PositiveIntegerField(db_index=True, verbose_name='Codigo do operador')),
                ('tp_evento', models.CharField(db_index=True, max_length=50, verbose_name='Tipo do evento')),
                ('nm_pausa', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Nome da pausa')),
                ('dt_inicio', models.DateTimeField(db_index=True, verbose_name='Data/hora de inicio')),
                ('dt_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data/hora de fim')),
                ('duracao_seg', models.IntegerField(blank=True, null=True, verbose_name='Duracao em segundos')),
                ('dt_captura_origem', models.DateTimeField(blank=True, null=True, verbose_name='Data/hora de captura na origem')),
                ('raw_payload', models.JSONField(blank=True, null=True, verbose_name='Payload bruto')),
                ('inserted_at', models.DateTimeField(auto_now_add=True, verbose_name='Inserido em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='monitoring.agent', verbose_name='Agente')),
            ],
            options={
                'verbose_name': 'Evento de agente',
                'verbose_name_plural': 'Eventos de agentes',
                'indexes': [models.Index(fields=['agent', 'dt_inicio'], name='idx_agevent_agent_dtini')],
                'constraints': [models.UniqueConstraint(fields=('source', 'source_event_hash'), name='uniq_agentevent_source_hash'), models.CheckConstraint(check=models.Q(('duracao_seg__isnull', True), ('duracao_seg__gte', 0), _connector='OR'), name='chk_agentevent_duracao_nonneg')],
            },
        ),
        migrations.CreateModel(
            name='NotificationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_operador', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Codigo do operador')),
                ('notification_type', models.CharField(choices=[('sem_pausa', 'Sem pausa'), ('muitas_pausas', 'Muitas pausas'), ('status_irregular', 'Status irregular'), ('supervisor_alerta', 'Supervisor alerta'), ('notificacao_generica', 'Notificacao generica')], max_length=50, verbose_name='Tipo de notificacao')),
                ('channel', models.CharField(choices=[('chatseguro', 'ChatSeguro'), ('email', 'E-mail'), ('teams', 'Microsoft Teams'), ('slack', 'Slack'), ('webhook', 'Webhook')], max_length=30, verbose_name='Canal')),
                ('recipient', models.CharField(max_length=200, verbose_name='Destinatario')),
                ('status', models.CharField(choices=[('SENT', 'Enviado'), ('ERROR', 'Erro'), ('SKIPPED', 'Ignorado')], max_length=20, verbose_name='Status')),
                ('error_message', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Mensagem de erro')),
                ('payload', models.JSONField(blank=True, null=True, verbose_name='Payload')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_history', to='monitoring.agent', verbose_name='Agente')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_history', to='messaging.messagetemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Historico de notificacao',
                'verbose_name_plural': 'Historico de notificacoes',
                'indexes': [models.Index(fields=['agent', 'notification_type', 'created_at'], name='idx_nothist_agent_type_dt'), models.Index(fields=['status', 'created_at'], name='idx_nothist_status_dt')],
            },
        ),
        migrations.CreateModel(
            name='NotificationThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('sem_pausa', 'Sem pausa'), ('muitas_pausas', 'Muitas pausas'), ('status_irregular', 'Status irregular'), ('supervisor_alerta', 'Supervisor alerta'), ('notificacao_generica', 'Notificacao generica')], max_length=50, verbose_name='Tipo de notificacao')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Ultimo envio em')),
                ('sent_count_today', models.PositiveIntegerField(default=0, verbose_name='Envios hoje')),
                ('day_ref', models.DateField(default=django.utils.timezone.localdate, verbose_name='Dia de referencia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_throttles', to='monitoring.agent', verbose_name='Agente')),
            ],
            options={
                'verbose_name': 'Controle de notificacao',
                'verbose_name_plural': 'Controles de notificacao',
                'constraints': [models.UniqueConstraint(fields=('agent', 'notification_type'), name='uniq_notifthr_agent_type')],
            },
        ),
    ]
