# Generated by Django 4.2.16 on 2026-03-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentWorkday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50, verbose_name='Fonte')),
                ('ext_event', models.BigIntegerField(verbose_name='Evento externo')),
                ('cd_operador', models.PositiveIntegerField(verbose_name='Codigo do operador')),
                ('nm_operador', models.CharField(max_length=255, verbose_name='Nome do operador')),
                ('work_date', models.DateField(verbose_name='Data de trabalho')),
                ('dt_inicio', models.DateTimeField(verbose_name='Data/hora de inicio')),
                ('dt_fim', models.DateTimeField(verbose_name='Data/hora de fim')),
                ('duracao_seg', models.IntegerField(verbose_name='Duracao em segundos')),
                ('dt_captura_origem', models.DateTimeField(blank=True, null=True, verbose_name='Data/hora de captura na origem')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='Payload bruto')),
                ('inserted_at', models.DateTimeField(auto_now_add=True, verbose_name='Inserido em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Jornada diaria do agente',
                'verbose_name_plural': 'Jornadas diarias dos agentes',
                'db_table': 'monitoring_agent_workday',
            },
        ),
        migrations.AddField(
            model_name='agentevent',
            name='ext_event',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Evento externo'),
        ),
        migrations.AddConstraint(
            model_name='agentevent',
            constraint=models.UniqueConstraint(condition=models.Q(('ext_event__isnull', False)), fields=('source', 'ext_event'), name='uq_agentevent_source_extevent'),
        ),
        migrations.AddIndex(
            model_name='agentworkday',
            index=models.Index(fields=['source', 'work_date'], name='idx_workday_source_date'),
        ),
        migrations.AddIndex(
            model_name='agentworkday',
            index=models.Index(fields=['cd_operador', 'work_date'], name='idx_workday_operador_date'),
        ),
        migrations.AddConstraint(
            model_name='agentworkday',
            constraint=models.UniqueConstraint(fields=('source', 'cd_operador', 'work_date'), name='uq_workday_source_operador_date'),
        ),
        migrations.AddConstraint(
            model_name='agentworkday',
            constraint=models.UniqueConstraint(fields=('source', 'ext_event'), name='uq_workday_source_extevent'),
        ),
    ]
