# Generated by Django 4.2.16 on 2026-03-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_agentworkday_agentevent_ext_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PauseClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, db_index=True, default='', help_text='Opcional. Vazio significa classificacao global (qualquer fonte).', max_length=30, verbose_name='Fonte')),
                ('pause_name', models.CharField(help_text='Nome da pausa conforme legado (ex.: nm_pausa).', max_length=50, verbose_name='Nome da pausa')),
                ('pause_name_normalized', models.CharField(db_index=True, editable=False, max_length=50, verbose_name='Nome da pausa normalizado')),
                ('category', models.CharField(choices=[('LEGAL', 'Legal'), ('NEUTRAL', 'Neutral'), ('HARMFUL', 'Harmful')], max_length=10, verbose_name='Categoria')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Classificacao de pausa',
                'verbose_name_plural': 'Classificacoes de pausa',
                'ordering': ['source', 'pause_name_normalized'],
                'indexes': [models.Index(fields=['source', 'is_active', 'pause_name_normalized'], name='idx_pauseclass_src_active_name')],
            },
        ),
        migrations.AddConstraint(
            model_name='pauseclassification',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('source', 'pause_name_normalized'), name='uq_pauseclass_source_name_active'),
        ),
    ]
