# Generated by Django 4.2.16 on 2026-03-25 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_pauseclassification_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentevent',
            options={'base_manager_name': 'objects', 'default_manager_name': 'objects', 'verbose_name': 'Evento de agente', 'verbose_name_plural': 'Eventos de agentes'},
        ),
        migrations.AlterModelOptions(
            name='agentworkday',
            options={'base_manager_name': 'objects', 'default_manager_name': 'objects', 'verbose_name': 'Jornada diaria do agente', 'verbose_name_plural': 'Jornadas diarias dos agentes'},
        ),
    ]
