# Generated by Django 4.2.16 on 2026-03-25 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('member', 'Membro'), ('manager', 'Gerente'), ('analyst', 'Analista'), ('viewer', 'Visualizador')], default='member', help_text='Permissão do usuário no workspace', max_length=20, verbose_name='Role')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Membro do Workspace',
                'verbose_name_plural': 'Membros dos Workspaces',
                'db_table': 'user_workspaces',
                'ordering': ['workspace', 'user'],
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do workspace', max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(help_text='Identificador único do workspace (URL-friendly)', max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='Descrição do workspace', verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, help_text='Se o workspace está ativo', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('members', models.ManyToManyField(related_name='workspaces', through='workspaces.UserWorkspace', to=settings.AUTH_USER_MODEL, verbose_name='Membros')),
            ],
            options={
                'verbose_name': 'Workspace',
                'verbose_name_plural': 'Workspaces',
                'db_table': 'workspaces',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='userworkspace',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspaces.workspace', verbose_name='Workspace'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['slug'], name='workspaces_slug_cac896_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['is_active'], name='workspaces_is_acti_88a65d_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['created_at'], name='workspaces_created_05cfe1_idx'),
        ),
        migrations.AddIndex(
            model_name='userworkspace',
            index=models.Index(fields=['user', 'workspace'], name='user_worksp_user_id_59cd80_idx'),
        ),
        migrations.AddIndex(
            model_name='userworkspace',
            index=models.Index(fields=['workspace', 'role'], name='user_worksp_workspa_1b2660_idx'),
        ),
        migrations.AddIndex(
            model_name='userworkspace',
            index=models.Index(fields=['created_at'], name='user_worksp_created_a32437_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userworkspace',
            unique_together={('user', 'workspace')},
        ),
    ]
