# Generated by Django 5.1.6 on 2026-02-27 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.CharField(max_length=100, unique=True, verbose_name='Chave')),
                ('config_value', models.TextField(verbose_name='Valor')),
                ('value_type', models.CharField(choices=[('string', 'String'), ('int', 'Inteiro'), ('bool', 'Booleano'), ('json', 'JSON'), ('time', 'Horario')], max_length=20, verbose_name='Tipo do valor')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descricao')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_system_configs', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Configuracao do sistema',
                'verbose_name_plural': 'Configuracoes do sistema',
                'ordering': ['config_key'],
            },
        ),
    ]
